[profile.ci]
# Print stdout/stderr for failed tests
failure-output = "immediate"
# Do not cancel the run on the first failure
fail-fast = false

[profile.ci.junit]
path = "junit.xml" # This is overridden by the CLI flag in the workflow